FROM node:16

# RUN apt-get update || : && apt-get install python -y

# Create and cd to new folder
WORKDIR /app

# Copy local package files into this directory
COPY package*.json ./

RUN npm install

RUN ["mkdir", "src"]

COPY ./src ./src

COPY tsconfig.json .

EXPOSE 4000

# RUN pip install pipenv

# WORKDIR /src/scripts

# RUN pipenv run init

# WORKDIR /app

RUN ["npm", "run", "build"]

CMD ["node", "./dist/index.js"]
