version: '3.7'

services:
  db:
    container_name: ksnap_db
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=ksnap_db
    ports:
      - '5432:5432'

  web:
    container_name: ksnap_web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      - DATABASE_URL
