#!/usr/bin/env python

from dotenv import load_dotenv

import postgresql
import os

from dotenv.main import dotenv_values, load_dotenv

load_dotenv()

# Load Database
db_url = os.environ["DATABASE_URL"]
db = postgresql.open(db_url)

print("Loaded data from .env...")

db.execute(
    """
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    """
)

print("Added UUID v4 extension...")

db.execute(
    """
    CREATE TABLE IF NOT EXISTS dates (
        ID UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
        DATE DATE NOT NULL DEFAULT NOW(),
        DESCRIPTION TEXT NOT NULL,
        IMAGE TEXT NOT NULL
    );
    """
)

print("Created database...")
