CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS dates (
        ID UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
        DATE DATE NOT NULL DEFAULT NOW(),
        DESCRIPTION TEXT NOT NULL,
        IMAGE TEXT NOT NULL
    );